name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_server_image:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        name: Check out code
      
      - name: Login to Docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build server image
        run: 'docker build -t fredericpinaud/mqtt-server-monit ./services/server/Dockerfile'
      
      - name: Push image on docker hub 
        run: 'docker push fredericpinaud/mqtt-server-monit:latest'
      
  
  build_client_image:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
        name: Check out code
      
      - name: Login to Docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build client image
        run: 'docker build -t fredericpinaud/mqtt-client-monit ./services/client/Dockerfile'
      
      - name: Push image on docker hub 
        run: 'docker push fredericpinaud/mqtt-client-monit:latest'

    